#!/bin/bash
git add . #tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name MakcaWhite
git config --global user.email m.javorskis@gmail.com
git commit -m "class_$1"
echo class_$1 uploaded
git push origin main
