#!/bin/bash
var=$(date +%F)
echo "$var"

git add . #tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name MakcaWhite
git config --global user.email m.javorskis@gmail.com
git commit -m "class_$var"
git push origin main
echo class_"$var" uploaded

